# Generated by Django 6.0.3 on 2026-03-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50, verbose_name='Тема')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('full_teчt', models.TextField(verbose_name='Полный текст')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
